apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: srinu7150/vidli-backend:1.0
          env:
            - name: DB_USER
              value: "DB_USER"
            - name: DB_PASSWORD
              value: "DB_PASSWORD"
            - name: DB_NAME
              value: "DB_NAME"
